### ISSUE TITLE
riscv-pk: Add support for building riscv-pk

### ISSUE THREAD

**Issue by vj-kumar** [vj-kumar/shakti-debian#3]
BBL image generation support is needed. It needs riscv-gnu-toolchain. Compilation has some issues.

**Comment by johnnavaj** [comment]
I can help you with this . But can you tell me which version of linux you are finalizing for this ? As riscv-gnu-toolchain is not stable even in master , it needs to be somewhere between to get the right headers and symbols.

**Comment by vj-kumar** [comment]
Thank you @johnnavaj. I will push my local changes to a branch and will let you know. BTW, the issue is only when building with deb helper. I did a out of tree build with master and it works just fine.  
  
-vj-

**Comment by vj-kumar** [comment]
@johnnavaj riscv-pk recipe is now available in master.

**Comment by vj-kumar** [comment]
Fixed. https://github.com/vj-kumar/shakti-debian/commit/d4be93a3ae8d8fcc494faa4ac69b6f254c11dada
